"""add attachments field

Revision ID: 019a770eedc0
Revises: 9602cb697f05
Create Date: 2025-06-06 17:49:18.932917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import TEXT, Column
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = '019a770eedc0'
down_revision = '9602cb697f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentpiece', sa.Column('attachments', JSONB, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contentpiece', 'attachments')
    # ### end Alembic commands ###
