"""Initial schema based on current models

Revision ID: 3eccd154b871
Revises:
Create Date: 2025-04-08 19:13:32.977030

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3eccd154b871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('linkedin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('linkedin_scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_linkedin_id'), 'user', ['linkedin_id'], unique=True)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_table('clientprofile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientprofile_company_name'), 'clientprofile', ['company_name'], unique=False)
    op.create_index(op.f('ix_clientprofile_created_at'), 'clientprofile', ['created_at'], unique=False)
    op.create_index(op.f('ix_clientprofile_updated_at'), 'clientprofile', ['updated_at'], unique=False)
    op.create_table('scheduledlinkedinpost',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.TEXT(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'FAILED', name='poststatus'), nullable=False),
    sa.Column('linkedin_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduledlinkedinpost_created_at'), 'scheduledlinkedinpost', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduledlinkedinpost_linkedin_post_id'), 'scheduledlinkedinpost', ['linkedin_post_id'], unique=False)
    op.create_index(op.f('ix_scheduledlinkedinpost_scheduled_at'), 'scheduledlinkedinpost', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduledlinkedinpost_status'), 'scheduledlinkedinpost', ['status'], unique=False)
    op.create_index(op.f('ix_scheduledlinkedinpost_updated_at'), 'scheduledlinkedinpost', ['updated_at'], unique=False)
    op.create_index(op.f('ix_scheduledlinkedinpost_user_id'), 'scheduledlinkedinpost', ['user_id'], unique=False)
    op.create_table('contentpiece',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idea', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('angle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'REVISION_REQUESTED', 'APPROVED', 'PUBLISHED', 'SCHEDULED', name='contentstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('review_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clientprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentpiece_created_at'), 'contentpiece', ['created_at'], unique=False)
    op.create_index(op.f('ix_contentpiece_title'), 'contentpiece', ['title'], unique=False)
    op.create_index(op.f('ix_contentpiece_updated_at'), 'contentpiece', ['updated_at'], unique=False)
    op.create_table('strategy',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_created_at'), 'strategy', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_title'), 'strategy', ['title'], unique=False)
    op.create_index(op.f('ix_strategy_updated_at'), 'strategy', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_updated_at'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_title'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_created_at'), table_name='strategy')
    op.drop_table('strategy')
    op.drop_index(op.f('ix_contentpiece_updated_at'), table_name='contentpiece')
    op.drop_index(op.f('ix_contentpiece_title'), table_name='contentpiece')
    op.drop_index(op.f('ix_contentpiece_created_at'), table_name='contentpiece')
    op.drop_table('contentpiece')
    op.drop_index(op.f('ix_scheduledlinkedinpost_user_id'), table_name='scheduledlinkedinpost')
    op.drop_index(op.f('ix_scheduledlinkedinpost_updated_at'), table_name='scheduledlinkedinpost')
    op.drop_index(op.f('ix_scheduledlinkedinpost_status'), table_name='scheduledlinkedinpost')
    op.drop_index(op.f('ix_scheduledlinkedinpost_scheduled_at'), table_name='scheduledlinkedinpost')
    op.drop_index(op.f('ix_scheduledlinkedinpost_linkedin_post_id'), table_name='scheduledlinkedinpost')
    op.drop_index(op.f('ix_scheduledlinkedinpost_created_at'), table_name='scheduledlinkedinpost')
    op.drop_table('scheduledlinkedinpost')
    op.drop_index(op.f('ix_clientprofile_updated_at'), table_name='clientprofile')
    op.drop_index(op.f('ix_clientprofile_created_at'), table_name='clientprofile')
    op.drop_index(op.f('ix_clientprofile_company_name'), table_name='clientprofile')
    op.drop_table('clientprofile')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_linkedin_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
