"""Add retry_count to ScheduledLinkedInPost

Revision ID: 93b1a9ea9f1f
Revises: 3eccd154b871
Create Date: 2025-04-10 17:27:02.263489

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '93b1a9ea9f1f'
down_revision = '3eccd154b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduledlinkedinpost', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduledlinkedinpost', 'retry_count')
    # ### end Alembic commands ###
