"""added new cols

Revision ID: 9602cb697f05
Revises: 93b1a9ea9f1f
Create Date: 2025-05-27 20:53:58.988399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9602cb697f05'
down_revision = '93b1a9ea9f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentpiece', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.alter_column('contentpiece', 'content_body',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('contentpiece', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_contentpiece_title', table_name='contentpiece')
    op.create_index(op.f('ix_contentpiece_due_date'), 'contentpiece', ['due_date'], unique=False)
    op.create_index(op.f('ix_contentpiece_scheduled_at'), 'contentpiece', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_contentpiece_status'), 'contentpiece', ['status'], unique=False)
    op.add_column('scheduledlinkedinpost', sa.Column('content_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scheduledlinkedinpost_content_id'), 'scheduledlinkedinpost', ['content_id'], unique=False)
    op.create_foreign_key(None, 'scheduledlinkedinpost', 'contentpiece', ['content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduledlinkedinpost', type_='foreignkey')
    op.drop_index(op.f('ix_scheduledlinkedinpost_content_id'), table_name='scheduledlinkedinpost')
    op.drop_column('scheduledlinkedinpost', 'content_id')
    op.drop_index(op.f('ix_contentpiece_status'), table_name='contentpiece')
    op.drop_index(op.f('ix_contentpiece_scheduled_at'), table_name='contentpiece')
    op.drop_index(op.f('ix_contentpiece_due_date'), table_name='contentpiece')
    op.create_index('ix_contentpiece_title', 'contentpiece', ['title'], unique=False)
    op.alter_column('contentpiece', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('contentpiece', 'content_body',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('contentpiece', 'scheduled_at')
    # ### end Alembic commands ###
