"""make content_id nullable in scheduledlinkedinpost

Revision ID: c3f6b5d13cdf
Revises: fd99a329875f
Create Date: 2025-05-26 09:17:29.166773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c3f6b5d13cdf'
down_revision = 'fd99a329875f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scheduledlinkedinpost_content_id'), 'scheduledlinkedinpost', ['content_id'], unique=False)
    op.drop_constraint('fk_scheduled_post_contentpiece', 'scheduledlinkedinpost', type_='foreignkey')
    op.create_foreign_key(None, 'scheduledlinkedinpost', 'contentpiece', ['content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduledlinkedinpost', type_='foreignkey')
    op.create_foreign_key('fk_scheduled_post_contentpiece', 'scheduledlinkedinpost', 'contentpiece', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_scheduledlinkedinpost_content_id'), table_name='scheduledlinkedinpost')
    # ### end Alembic commands ###
