"""initial migration

Revision ID: e86041552d83
Revises: 
Create Date: 2025-05-27 16:06:45.389433

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e86041552d83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contentlinkedinpost_content_id', table_name='contentlinkedinpost')
    op.drop_index('ix_contentlinkedinpost_id', table_name='contentlinkedinpost')
    op.drop_index('ix_contentlinkedinpost_scheduled_at', table_name='contentlinkedinpost')
    op.drop_index('ix_contentlinkedinpost_status', table_name='contentlinkedinpost')
    op.drop_index('ix_contentlinkedinpost_user_id', table_name='contentlinkedinpost')
    op.drop_table('contentlinkedinpost')
    op.alter_column('contentpiece', 'content_body',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('contentpiece', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('contentpiece', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_contentpiece_title', table_name='contentpiece')
    op.create_index(op.f('ix_contentpiece_due_date'), 'contentpiece', ['due_date'], unique=False)
    op.create_index(op.f('ix_contentpiece_scheduled_at'), 'contentpiece', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_contentpiece_status'), 'contentpiece', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contentpiece_status'), table_name='contentpiece')
    op.drop_index(op.f('ix_contentpiece_scheduled_at'), table_name='contentpiece')
    op.drop_index(op.f('ix_contentpiece_due_date'), table_name='contentpiece')
    op.create_index('ix_contentpiece_title', 'contentpiece', ['title'], unique=False)
    op.alter_column('contentpiece', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('contentpiece', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('contentpiece', 'content_body',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('contentlinkedinpost',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('linkedin_post_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contentpiece.id'], name='contentlinkedinpost_content_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='contentlinkedinpost_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contentlinkedinpost_pkey')
    )
    op.create_index('ix_contentlinkedinpost_user_id', 'contentlinkedinpost', ['user_id'], unique=False)
    op.create_index('ix_contentlinkedinpost_status', 'contentlinkedinpost', ['status'], unique=False)
    op.create_index('ix_contentlinkedinpost_scheduled_at', 'contentlinkedinpost', ['scheduled_at'], unique=False)
    op.create_index('ix_contentlinkedinpost_id', 'contentlinkedinpost', ['id'], unique=False)
    op.create_index('ix_contentlinkedinpost_content_id', 'contentlinkedinpost', ['content_id'], unique=False)
    # ### end Alembic commands ###
